from django.db import models

class Technique(models.Model):
    # ID as primary key will be generated by default
    viewed_technique = models.BooleanField(default=False, null=False, blank=False)
    belt_prog = models.CharField(max_length=50, null=False, blank=False)
    uv = models.CharField(max_length=150, null=False, blank=False)
    category = models.CharField(max_length=150, null=False, blank=False)
    sub_category = models.CharField(max_length=150, null=False, blank=False)
    position = models.CharField(max_length=50, null=False, blank=False)
    technique = models.TextField(null=False, blank=False)
    viewed_date = models.DateField(null=True, blank=True)
    revision_date = models.DateField(null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    official_book_ref_page = models.PositiveIntegerField(null=True, blank=True)
    official_prog_ref_2025 = models.CharField(max_length=50)

    class Meta:
        indexes = [
            models.Index(fields=['belt_prog']),
            models.Index(fields=['uv']),
            models.Index(fields=['category']),
            models.Index(fields=['sub_category']),
        ]